tools:
  structural_searcher:
    signature: |
      structural_searcher <command> <project> [<entity>] [<code_snippet>]
    docstring: >
      Structure-aware search tool for jumping directly to class/function/method definitions or locating full code blocks by snippet.
    arguments:
      - name: command
        type: string
        description: "The command to run: either `locate_entity` or `find_code`."
        required: true
        enum: ["locate_entity", "find_code"]
      - name: project
        type: string
        description: "Absolute path to the project root (with Python source files). (e.g. '/testbed')"
        required: true
      - name: entity
        type: string
        description: "The name of the class/function/method to look up. Required if command is `locate_entity`."
        required: false
        argument_format: "--entity {{value}}"
      - name: code_snippet
        type: string
        description: "The snippet to locate. Required if command is `find_code`."
        required: false
        argument_format: "--code_snippet {{value}}"
state_command: "_state_anthropic"
