tools:
  structural_searcher:
    signature: |
      structural_searcher <command> <value> [<path>] [<file>]
    docstring: >
      Structure-aware search tool that allows jumping directly to class/function/method 
      definitions, locating function/methods containing a code snippet, or finding a file/module 
      path within a Python project.
    arguments:
      - name: command
        type: string
        description: >
          The sub-command to run. 
          * `find_file`: find a filename or module path under the directory.
          * `search_entity`: locate a class/function/method in a Python file.
          * `find_code`: locate a code block containing a specific snippet.
        required: true
        enum: ["find_file", "search_entity", "find_code"]

      - name: value
        type: string
        description: >
          The target string to look for.
          * If `find_file`: the filename or module path.
          * If `search_entity`: the class/function/method name.
          * If `find_code`: the code snippet to locate.
        required: true

      - name: path
        type: string
        description: >
          Root path to start the search. Defaults to current directory.
        required: false
        argument_format: "--path {{value}}"

      - name: file
        type: string
        description: >
          File path. Required for `search_entity` and `find_code`.
        required: false
        argument_format: "--file {{value}}"

state_command: "_state_anthropic"
